# Generated by Django 4.0.5 on 2022-06-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_teacher_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='qualification',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
