# Generated by Django 4.0.5 on 2022-06-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teacher_qualification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='address',
            new_name='skills',
        ),
    ]
