# Generated by Django 4.0.5 on 2022-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_address_teacher_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='skills',
            field=models.TextField(max_length=200),
        ),
    ]
