# Generated by Django 4.0.1 on 2022-07-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_student_options_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='video',
        ),
        migrations.AddField(
            model_name='chapter',
            name='video_url',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='main.course'),
        ),
    ]
